'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("MultiDrive.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to FATAL ERROR.
        '''</summary>
        Public ReadOnly Property ExceptionType_FATAL_ERROR() As String
            Get
                Return ResourceManager.GetString("ExceptionType_FATAL_ERROR", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to delete.
        '''</summary>
        Public ReadOnly Property ImageKey_delete() As String
            Get
                Return ResourceManager.GetString("ImageKey_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to download.
        '''</summary>
        Public ReadOnly Property ImageKey_download() As String
            Get
                Return ResourceManager.GetString("ImageKey_download", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to open.
        '''</summary>
        Public ReadOnly Property ImageKey_open() As String
            Get
                Return ResourceManager.GetString("ImageKey_open", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to rename.
        '''</summary>
        Public ReadOnly Property ImageKey_rename() As String
            Get
                Return ResourceManager.GetString("ImageKey_rename", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to star.
        '''</summary>
        Public ReadOnly Property ImageKey_star() As String
            Get
                Return ResourceManager.GetString("ImageKey_star", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to trash.
        '''</summary>
        Public ReadOnly Property ImageKey_trash() As String
            Get
                Return ResourceManager.GetString("ImageKey_trash", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;html&gt;
        '''  &lt;head&gt;
        '''    &lt;title&gt;{APP} - OAuth Authentication&lt;/title&gt;
        '''  &lt;/head&gt;
        '''  &lt;body&gt;
        '''    &lt;h1&gt;Authorization for {APP}&lt;/h1&gt;
        '''    &lt;p&gt;The application has received your response. You can close this window now.&lt;/p&gt;
        '''    &lt;script type=&apos;text/javascript&apos;&gt;
        '''      window.setTimeout(function() { window.open(&apos;&apos;, &apos;_self&apos;, &apos;&apos;); window.close(); }, 100);
        '''      if (window.opener) { window.opener.checkToken(); }
        '''     &lt;/script&gt;
        '''  &lt;/body&gt;
        '''&lt;/html&gt;.
        '''</summary>
        Public ReadOnly Property LoopbackServerHtmlResponse() As String
            Get
                Return ResourceManager.GetString("LoopbackServerHtmlResponse", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Click OK to remove the following users: .
        '''</summary>
        Public ReadOnly Property Message_Click_OK_to_remove_the_following_users() As String
            Get
                Return ResourceManager.GetString("Message_Click_OK_to_remove_the_following_users", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Error!.
        '''</summary>
        Public ReadOnly Property Message_Error_Exclamation() As String
            Get
                Return ResourceManager.GetString("Message_Error_Exclamation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Invalid Chunk-Size.
        '''</summary>
        Public ReadOnly Property Message_Invalid_chunk_size() As String
            Get
                Return ResourceManager.GetString("Message_Invalid_chunk_size", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delete files?.
        '''</summary>
        Public ReadOnly Property Message_question_Delete_file() As String
            Get
                Return ResourceManager.GetString("Message_question_Delete_file", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Are you sure you want to permanently delete the selected file(s) (skip the trash?).
        '''</summary>
        Public ReadOnly Property Message_question_perm_delete() As String
            Get
                Return ResourceManager.GetString("Message_question_perm_delete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove User(s) Confirmation.
        '''</summary>
        Public ReadOnly Property Message_Remove_users_confirmation() As String
            Get
                Return ResourceManager.GetString("Message_Remove_users_confirmation", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Save selected files to....
        '''</summary>
        Public ReadOnly Property Message_Save_selected_files_to() As String
            Get
                Return ResourceManager.GetString("Message_Save_selected_files_to", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
